MukConnect/MukConnect/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('base.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MukConnect/base/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('',views.home,name='home'),
    path('login',views.login_user,name='login'),
    path('logout',views.logout_user,name='logout'),
    path('signup',views.signup,name='signup'),
    path('booking',views.booking,name='booking'),
    path('hostel_detail/<int:pk>/',views.hostel_detail,name='hostel_detail'),
    
]

MukConnect/base/models.py
from django.db import models

# Create your models here.

class University(models.Model):
    name=models.CharField(max_length=200)

    class Meta:
        verbose_name_plural='Universities'
    
    def __str__(self):
        return self.name

class Area(models.Model):
    university=models.ForeignKey(University,on_delete=models.CASCADE,default='')
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Hostel(models.Model):
    area=models.ForeignKey(Area,on_delete=models.CASCADE,default='')
    name=models.CharField(max_length=200,blank=True)
    image_1=models.ImageField(upload_to='hostel_pictures',default='',blank=True,null=True)
    image_2=models.ImageField(upload_to='hostel_pictures',default='',blank=True,null=True)
    image_3=models.ImageField(upload_to='hostel_pictures',default='',blank=True,null=True)
    mtn_contact=models.CharField(max_length=20,blank=True,null=True)
    airtel_contact=models.CharField(max_length=20,blank=True,null=True)
    email=models.EmailField(default='',blank=True,null=True)
    is_full=models.BooleanField(default=False)
    free_rooms = models.IntegerField(default=0)


    def __str__(self):
        return self.name

class RoomCapacity(models.Model):
    name=models.CharField(max_length=20)

    def __str__(self):
        return self.name

    
class Room(models.Model):
    hostel=models.ForeignKey(Hostel,on_delete=models.CASCADE,default='')
    room_number=models.CharField(max_length=20,default='')
    capacity=models.ForeignKey(RoomCapacity,on_delete=models.CASCADE,default='')
    is_self_contained=models.BooleanField(default=False)
    price=models.IntegerField(default=0)
    booking_fee=models.IntegerField(default=0)
    is_occupied=models.BooleanField(default=False)
    available_bed_spaces=models.IntegerField(default=0)

    def __str__(self):
        return self.room_number

MukConnect/base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username','email','password1','password2')

    
        

MukConnect/base/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.models import User
from . forms import *
from . models import*

# Create your views here.

def home(request):
    if request.user.is_authenticated:
        user = request.user
        return render(request, 'base/home.html', {'user': user})
    else:
        messages.success(request,'You are Currently logged out')
        return redirect('login')
    

def login_user(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            messages.success(request,'You have been logged in successfully')
            return redirect('home')
        else:
            messages.error(request,'Invalid Credentials, Please try again')
            return redirect('login')
    else:
        return render(request,'base/login.html')


def logout_user(request):
    logout(request)
    return redirect('login')

def signup(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Your Account has been created successfully')
            
           
            return redirect('login')
        else:
            for msg in form.error_messages:
                messages.error(request,f'{msg}: {form.error_messages[msg]}')
            return render(request,'base/signup.html',{'form':form})
    else:
        form=UserCreationForm()

    return render(request,'base/signup.html',{'form':form})





def booking(request):
    universities = University.objects.all()
    q = request.GET.get('q')
    hostels = Hostel.objects.filter(name=q)

    university_areas_hostels = {}
    for university in universities:
        areas = university.area_set.all()
        area_hostels = {}
        for area in areas:
            area_hostels[area] = area.hostel_set.all()
        university_areas_hostels[university] = area_hostels

    return render(request, 'base/bookings.html', {'university_areas_hostels': university_areas_hostels, 'selected_hostel': hostels.first()})


def hostel_detail(request,pk):
    hostel=Hostel.objects.get(id=pk)
    return render(request,'base/hostel_detail.html',{'hostel':hostel})

MukConnect/base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Muk Connect</title>

<style>
  *{
    margin-top: 1px;
    margin-left: 0px;
    margin-right: 0px;
  }
    .cool-nav {
  background-color: #2ecc71; /* Nice green color */
  list-style: none; /* Remove default bullet points */
  padding: 10px 20px; /* Add some padding */
  border-radius: 5px; /* Rounded corners */
  text-align: center; /* Center the links horizontally */
}

.cool-nav li {
  display: inline-block; /* Display links inline */
  margin: 0 15px; /* Add space between links */
}

.cool-nav a {
  color: white; /* White text */
  text-decoration: none; /* Remove underline */
  font-weight: bold; /* Bold text */
  transition: color 0.3s ease-in-out; /* Smooth hover effect */
}

.cool-nav a:hover {
  color: #1f8b41; /* Darker green on hover */
}


.black-footer {
  background-color: black;
  color: white; /* White text for contrast */
  padding: 20px;
  text-align: center; /* Center the content horizontally */
}

.messages{
  display: block; /* Make elements fill the full width */
  width: 100%; /* Set width to 100% of the form */
  text-align: center; /* Center text content within each element */
  margin-bottom: 1px; /* Add some space between elements */
  color: Red;
  font-size: large;
}


</style>

</head>
<body>
    <nav class="cool-nav">
        {%if user.is_authenticated%}
        <ul>
          <li><a href="{% url 'home'%}">Home</a></li>
          <li><a href="{% url 'booking'%}">Bookings</a></li>
          <li><a href="{% url 'logout'%}">Logout</a></li>
          {%else%}
          <li><a href="{% url 'login'%}">Login</a></li>
          <li><a href="{%url 'signup'%}">Sign Up</a></li>
        </ul>
        {%endif%}
      </nav>

      {%for message in messages%}
      <div class="messages">
        {{message}}
      </div>
     
      {%endfor%}
      

    {% block content%}

    {% endblock %}

    <!-- <footer class="black-footer">
        <p>© 2024 Muk Connect</p>
        </footer> -->
      
    
</body>
</html>

MukConnect/base/templates/base/bookings.html
{% extends 'base/base.html'%}
{% block content%}

<style>
    a{
        text-decoration: none;
        
    }
    body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }
    .container {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        height: 100vh;
        padding: 20px;
    }
    .left {
        flex: 1;
        background-color: #f2f2f2;
        padding: 20px;
    }
    .middle {
        flex: 2;
        background-color: #e0e0e0;
        padding: 20px;
    }
    .right {
        flex: 1;
        background-color: #d3d3d3;
        padding: 20px;
    }
    .middle {
    flex: 2;
    background-color: #e0e0e0;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.middle h2 {
    font-size: 24px;
    margin-bottom: 15px;
}

.middle p {
    font-size: 16px;
    margin-bottom: 10px;
}

.middle button {
    padding: 10px 20px;
    font-size: 16px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.middle button:hover {
    background-color: #45a049;
}
.middle img {
    width: 170px; /* Adjust the maximum width as needed */
    height: 150px; /* Adjust the maximum height as needed */
    margin-bottom: 10px; /* Add some margin below each image */
    margin-right: 15px;
}
.room-types {
    margin-top: 20px; /* Add some top margin for spacing */
}

.room-types h3 {
    font-size: 18px;
    margin-bottom: 10px; /* Add some bottom margin to the heading */
}

.room-types ul {
    list-style-type: none; /* Remove default list styles */
    padding-left: 0; /* Remove default left padding */
}

.room-types li {
    margin-bottom: 5px; /* Add some bottom margin between each list item */
    font-size: 16px;
}

</style>


<div class="container">
    <div class="left">
        <h2>University</h2>
        {% for university, areas_hostels in university_areas_hostels.items %}
        <h2>{{ university.name }}</h2>
        {% for area, hostels in areas_hostels.items %}
            <h3>{{ area.name }}</h3>
            <ul>
            {% for hostel in hostels %}
            <a href="{%url 'booking'%}?q={{hostel.name}}"><li>{{ hostel.name }}- {{ hostel.free_rooms }} free rooms</li></a>
                
            {% endfor %}
            </ul>
        {% endfor %}
    {% endfor %}
    

        
    </div>
    
    <div class="middle">
        <!-- Middle Content -->
        <h3>Images</h3>
            {% if selected_hostel.image_1 %}
                <img src="{{ selected_hostel.image_1.url }}" alt="Image 1">
            {% endif %}
            {% if selected_hostel.image_2 %}
                <img src="{{ selected_hostel.image_2.url }}" alt="Image 2">
            {% endif %}
            {% if selected_hostel.image_3 %}
                <img src="{{ selected_hostel.image_3.url }}" alt="Image 3">
            {% endif %}
        {% if selected_hostel %}
            <h2>{{ selected_hostel.name }}</h2>
            <p>Area: {{ selected_hostel.area }}</p>
            
            <p>Mtn Contact: {{ selected_hostel.mtn_contact }}</p>
            <p>Airtel Contact: {{ selected_hostel.airtel_contact }}</p>
            <p>Email: {{ selected_hostel.email }}</p>
            <p>Free rooms: {{ selected_hostel.free_rooms}}</p>
            <a href=""><button>More details</button></a>
            
            <h3 class="room-types">Room Types</h3>
<ul class="room-types">
    {% for room in selected_hostel.room_set.all %}
        <li>Room Number: {{ room.room_number }}</li>
        <li>Capacity: {{ room.capacity }}</li>
        <li>Price: {{ room.price }}</li>
        <li>Booking Fee: {{ room.booking_fee }}</li>
        <li>Self Contained: {% if room.is_self_contained %}Yes{% else %}No{% endif %}</li>
        <li>Occupied: {% if room.is_occupied %}Yes{% else %}No{% endif %}</li>
        <li>Available bed spaces: {{ room.available_bed_spaces }}</li>
        
        <div><button>Book Now</button></div>
    {% endfor %}
</ul>

            
            
        {% else %}
            <h2>No hostel selected</h2>
        {% endif %}
    </div>
    
    <div class="right">
        <h2>Right Content</h2>
        <h2>Description</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi error deleniti, praesentium quibusdam labore commodi molestias omnis doloribus quisquam unde illum numquam dolorem nisi molestiae illo officia optio dolores magnam.</p>
        
    </div>
</div>



{%endblock%}

MukConnect/base/templates/base/home.html
{% extends 'base/base.html'%}
{% block content%}
<h1>Welcome {{user.username}}</h1>
{%endblock%}

MukConnect/base/templates/base/hostel_detail.html
{% extends 'base/base.html'%}
{% block content%}

{{hostel.name}}


{%endblock%}

MukConnect/base/templates/base/login.html
{% extends 'base/base.html'%}
{% block content%}

<style>
    .login-form {
  margin: 0 auto; /* Center horizontally */
  padding: 20px; /* Add some padding */
  border: 1px solid #ddd; /* Optional: Add a border */
  border-radius: 5px; /* Optional: Add rounded corners */
  background-color: #f1f1f1; /* Optional: Add a background color */
  max-width: 400px; /* Optional: Set a maximum width */
  height: 350px;
}

.login-form label,
.login-form input[type="text"],
.login-form input[type="password"]
 {
  display: block; /* Make elements fill the full width */
  width: 100%; /* Set width to 100% of the form */
  text-align: center; /* Center text content within each element */
  margin-bottom: 5px; /* Add some space between elements */
}
button{
    background-color: rgb(23, 181, 71);
    height: 50px;
    width: 100%;
    border-radius: 8px;
    margin-left: 4px;
    cursor: pointer;
    border: none;
    transition: opacity 0.5s;
}

button:hover{
    opacity: 0.8;
}

.login-form input[type="text"],
.login-form input[type="password"]{
    height: 30px;
    border-radius: 20px;
}
.login-form label{
    font-size: x-large;
    font-weight: bolder;
}
p{
    display: block; /* Make elements fill the full width */
  width: 100%; /* Set width to 100% of the form */
  text-align: center; /* Center text content within each element */
  margin-bottom: 10px; /* Add some space between elements */  
  font-size: large;
    font-weight: bolder;
}


</style>
<br><br>

<div class="login-form">

    <form action="" method="POST">
        {%csrf_token%}
        <label for="">Username</label><br>
        <input type="text" name="username"><br>
        <label for="">Password</label><br>
        <input type="password" name="password"><br>
        <button type="submit">Login</button>

        <p>Don't have an Account? <a href="{%url 'signup'%}">Signup</a></p>
        <p><a href="">Forgot Password</a></p>
    
    </form>

</div>

<br><br>


{% endblock %}

MukConnect/base/templates/base/signup.html
{% extends 'base/base.html'%}
{% block content%}

<style>
    .signup-form {
  margin: 0 auto; /* Center horizontally */
  padding: 20px; /* Add some padding */
  border: 1px solid #ddd; /* Optional: Add a border */
  border-radius: 5px; /* Optional: Add rounded corners */
  background-color: #f1f1f1; /* Optional: Add a background color */
  max-width: 400px; /* Optional: Set a maximum width */
 
}

.signup-form label,
.signup-form input[type="text"],
.signup-form input[type="password"]
 {
  display: block; /* Make elements fill the full width */
  width: 100%; /* Set width to 100% of the form */
  text-align: center; /* Center text content within each element */
  margin-bottom: 5px; /* Add some space between elements */
}
button{
    background-color: rgb(23, 181, 71);
    height: 50px;
    width: 100%;
    border-radius: 8px;
    margin-left: 4px;
    cursor: pointer;
    border: none;
    transition: opacity 0.5s;
}

button:hover{
    opacity: 0.8;
}

.signup-form input[type="text"],
.signup-form input[type="password"]{
    height: 30px;
    border-radius: 20px;
}
.signup-form label{
    font-size: x-large;
    font-weight: bolder;
}
p{
    display: block; /* Make elements fill the full width */
  width: 100%; /* Set width to 100% of the form */
  text-align: center; /* Center text content within each element */
  margin-bottom: 10px; /* Add some space between elements */  
  font-size: large;
    font-weight: bolder;
}


</style>
<br>

<div class="signup-form">
    <form action="" method="POST">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Sign Up</button>
        <p>Already have an Account <a href="{%url 'login'%}">Login</a></p>
    </form>
    
</div>
<br><br><br><br>
{%endblock%}